language: php
php:
  - 7.4

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "hulkthedev"

git:
  depth: false

install:
  - gem install travis

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - travis login
  - travis encrypt 54daf9510c506a7c0c7d9498deb802b4b54e0ce5

script:
  - phpunit -c tests --coverage-clover=clover.xml --log-junit junit.xml
  - sonar-scanner
