language: php
php:
  - 7.4

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache
git:
  depth: false

addons:
  sonarcloud:
    organization: "hulkthedev"
    token:
      secure: 8104e369626a22af4270704ad559bc5973212b09

#install:
#  - gem install travis

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
#  - travis login
#  - travis encrypt ENCRYPTED_TOKEN=dbfa02ff2cfd447adeb53318eb7288793414d636 --add
#  - echo $ENCRYPTED_TOKEN

script:
  - phpunit -c tests --coverage-clover=clover.xml --log-junit junit.xml
  - sonar-scanner -X