language: php
php:
  - 7.4

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "hulkthedev"

git:
  depth: false

install:
  - gem install travis

before_script:
#  - travis_retry composer self-update
#  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - travis login
  - travis encrypt dbfa02ff2cfd447adeb53318eb7288793414d636 --add

script:
  - phpunit -c tests --coverage-clover=clover.xml --log-junit junit.xml
  - sonar-scanner
