language: php
php:
  - 7.4

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache
git:
  depth: false

install:
  - gem install travis

before_script:
  - travis login
  - travis encrypt dbfa02ff2cfd447adeb53318eb7288793414d636 --add
